### ISSUE TITLE
Component Schemas in the OpenAPI spec using additionalProperties are not always correctly used

### ISSUE THREAD

**Issue by mstab** [ai4you-io/openedge-abl-openapi#10]
The current implementation does not handle untyped component schemas with `additionalProperties`.
This requires some JSON helper methods for extracting all data from JSON.

```YAML
...
components:
    schemas:
      Attachment_headers:
        type: object
        properties:
          empty:
            type: boolean
        additionalProperties:
          type: array
          items:
            type: string
```

This spec currently ignores the additionalProperties, making the model incomplete.
